<script src="{{ asset('admin_assets/ar/global/plugins/jquery-ui/jquery-ui.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('admin_assets/ar/global/plugins/bootstrap/js/bootstrap.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('admin_assets/ar/global/plugins/bootstrap-hover-dropdown/bootstrap-hover-dropdown.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('admin_assets/ar/global/plugins/jquery-slimscroll/jquery.slimscroll.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('admin_assets/ar/global/plugins/jquery.blockui.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('admin_assets/ar/global/plugins/jquery.cokie.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('admin_assets/ar/global/plugins/uniform/jquery.uniform.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('admin_assets/ar/global/plugins/bootstrap-switch/js/bootstrap-switch.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('admin_assets/ar/global/scripts/metronic.js') }}" type="text/javascript"></script>
<script src="{{ asset('admin_assets/ar/admin/layout/scripts/layout.js') }}" type="text/javascript"></script>
<script src="{{ asset('admin_assets/ar/admin/layout/scripts/quick-sidebar.js') }}" type="text/javascript"></script>
<script src="{{ asset('admin_assets/ar/admin/layout/scripts/demo.js') }}" type="text/javascript"></script>